#ifndef LUH_YOUBOT_MSGS_INTERPOLATION_MODE_H
#define LUH_YOUBOT_MSGS_INTERPOLATION_MODE_H

namespace arcl_youbot_msgs
{
enum InterpolationMode
{
    JOINTSPACE,
    CYLINDRIC,
    CARTESIAN
};
}

#endif //LUH_YOUBOT_MSGS_INTERPOLATION_MODE_H
